---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-model
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate
reclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: model-cache-nfs-pv
spec:
  capacity:
    storage: 300Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-model
  mountOptions:
    - nolock
    - nfsvers=4.1
  nfs:
    # Replace with the actual IP address of your NFS server (clusterIP of nfs-server service)
    server: 172.16.4.193 
    path: /
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-cache-rwx
  namespace: vllm
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 300Gi
  storageClassName: nfs-model
  volumeName: model-cache-nfs-pv